### ISSUE TITLE
Crosshair on Third Person View

### ISSUE THREAD

**Issue by ardissaps** [henkelmax/camera-utils#17] opened 2022-06-10 04:05 UTC
**Is your feature request related to a problem? Please describe.**
No crosshair when using bow on 3rd person

**Describe the solution you'd like**
3rd Person Cursor (movable)

**Describe alternatives you've considered**
Option to force enable crosshair

**Additional context**
Thanks!

**Comment by henkelmax** [comment] 2022-06-10 05:33
Duplicate of #10

**Closed by henkelmax** 2022-06-10 05:33 UTC
Labels: enhancement
