### ISSUE TITLE
Camera Interacts with the blocks (Feature)

### ISSUE THREAD

**Issue by ALPHAGAMER42** [henkelmax/camera-utils#51] opened 2023-06-22 12:32 UTC
The main problem with my modpack is the 3rd person camera just goes inside the blocks kinda make them usefull for xrays it would be cool if we had option or a feature of camera interacting with the blocks

**Comment by henkelmax** [comment] 2023-06-22 15:17
Duplicate of #6

**Closed by henkelmax** 2023-06-22 15:17 UTC
Labels: enhancement
