### ISSUE TITLE
camera immersion in blocks when using custom 3rd person view

### ISSUE THREAD

**Issue by KRABEF** [henkelmax/camera-utils#39] opened 2023-01-13 18:07 UTC
**Is your feature request related to a problem? Please describe.**
Abused viewing through blocks on servers => illegal use of the mod on servers => problems with using the mod on multiplayer servers

**Describe the solution you'd like**
Make the camera more fair for playing on multiplayer servers

**Describe alternatives you've considered**
Make the camera behave like in vanilla minecraft, so that the camera does not go underground, but remains on the surface

**Additional context**
1 screenshot - mod camera
2 screenshot - vanilla camera
3 screenshot - bruh moment

Sry for  unknowing of English :))))

![Desktop Screenshot 2023 01 13 - 23 06 30 08](https://user-images.githubusercontent.com/119063987/212389695-691ebb97-d568-4e28-b0db-d89837ddea5a.png)
![Minecraft Screenshot 2023 01 13 - 22 39 34 42](https://user-images.githubusercontent.com/119063987/212385294-f1a72322-b8a3-4520-a860-499e2c3c8104.png)
![Minecraft Screenshot 2023 01 13 - 22 54 39 80](https://user-images.githubusercontent.com/119063987/212387595-681a6eb8-b33a-4158-846a-81d8c813105c.png)

**Comment by henkelmax** [comment] 2023-01-13 18:10
Duplicate of #6

**Closed by henkelmax** 2023-01-13 18:10 UTC
Labels: enhancement
