### ISSUE TITLE
Unexpected behavior when zoom is set to either Alt key

### ISSUE THREAD

**Issue by ShyVaporeon** [henkelmax/camera-utils#52] opened 2023-07-03 20:07 UTC
**Bug description**
Setting Zoom function to the Alt key, results in the Alt key opening the zoom menu instead.
I believe this is because the Alt key is hard coded as a modifier key. 

Setting the zoom key as Left Alt is a good idea because it is easy to press while holding asdw and is easy to reach in general.

This issue occurs with both the Left Alt key and the Right Alt key.
I testes my keyboard to see what key is sent when Left Alt is pressed, and it seems like both Alt keys are being sent when Left Alt is pressed.
Not sure if this is an issue caused on my end but, it would be nice to be able to configure the Modifier key either way.

Also, great mod and thank you for making it :)

**Versions**
- Minecraft 1.19.2
- Mod version 1.0.3

**Comment by henkelmax** [comment] 2023-07-03 20:27
Duplicate of #37

**Closed by henkelmax** 2023-07-03 20:27 UTC
Labels: bug
