### ISSUE TITLE
Windows Defender issue

### ISSUE THREAD

**Issue by Dreig-Michihi** [henkelmax/camera-utils#61] opened 2024-03-18 12:07 UTC
### Bug description

Shows the mod has a trojan. Being deleted automatically.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.0.9

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

Get the mod with Modrinth App with Microsoft Defender enabled.

### Expected behavior

It was one of my favourite mod, why the hell there is a trojan found idk, it makes me upset.

### Log files

https://gist.github.com/.

### Screenshots

![image](https://github.com/henkelmax/camera-utils/assets/60939608/fea98ae8-5121-444a-a848-5e2a73104bf8)

**Comment by henkelmax** [comment] 2024-03-18 13:58
Duplicate of #60

**Closed by henkelmax** 2024-03-18 13:58 UTC
Labels: triage
