### ISSUE TITLE
FOV is higher than usual with speed effect

### ISSUE THREAD

**Issue by MichaMvz** [henkelmax/camera-utils#19] opened 2022-07-03 13:52 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/camerautils/faq) before submitting a bug report!**

**Bug description**
The camera utils mod causes FOV to go crazy when given a speed effect of over 8

**Steps to reproduce the issue**
1. Have the camera utils mod installed on 1.19
2. give yourself a speed effect of 9 or higher

**Expected behavior**
Not make your FOV go crazy/dissapear

**Log files**
[latest.log](https://github.com/henkelmax/camera-utils/files/9034869/latest.log)

**Versions**
- Minecraft version: **1.19**
- Fabric loader version: **0.14.7**
- Mod version: **camerautils-1.19-1.0.0**

**Other mods**
Mod works when loaded without any other mods, my mod list is:
        - advancementinfo 1.19-fabric0.53.3-1.3.1
	- antighost 1.19-fabric0.55.3-1.1.5
	- appleskin 2.4.0+mc1.19
	- architectury 5.7.27
	- autoclicker-fabric 1.19-1.4.0-build.17
	- badpackets 0.1.2
	- beenfo 1.19-fabric0.53.3-1.3.3
	- betterbeds 1.2.0
	- bettercommandblock 2.5.10
	- bettermounthud 1.1.4
	- betterpingdisplay 1.1.1
	- betterthirdperson 1.8.1
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- bobby 4.0.0
	- bookshelf 14.0.3
	- boostedbrightness 2.1.2
	- borderlessmining 1.1.4+1.19
	- bsvsb 3.0.0
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- camerautils 1.19-1.0.0
	- capes 1.4.2+1.19
	- cem 0.7.1
	- citresewn 1.1.0+1.19
	- citresewn-defaults 1.1.0+1.19 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.72
	- collective-fabric 4.27
	- colormatic 3.1.2+mc.1.19
	- com_github_llamalad7_mixinextras 0.0.10 via cull-less-leaves
	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_typesafe_config 1.4.2 via bobby
	- completeconfig-base 2.0.0-beta.3 via cem
	- completeconfig-gui-cloth 2.0.0-beta.3 via cem
	- continuity 2.0.0+1.19
	- crowdin-translate 1.4+1.19 via antighost
	- cull-less-leaves 1.0.2
	- cullleaves 2.3.4
	- dashloader 4.0.0+1.19
	- dcch 1.2
	- debugify 2.1.0
	- dev_isxander_settxi_settxi-core 2.3.0 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.3.0 via zoomify
	- dev_quantumfusion_hyphen 0.2.2 via dashloader
	- dev_quantumfusion_taski 1.1.0 via dashloader
	- dynamicfps 2.2.0
	- easierchests 1.19-fabric0.53.3-1.7.0
	- effective 1.2.2
	- effectsleft 0.1.1
	- entity_texture_features 3.1.2
	- entityculling 1.5.2-mc1.19
	- fabric 0.56.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via bobby
	- fabricloader 0.14.7
	- fabrishot 1.8.0
	- fallingleaves 1.12.1+1.19
	- farsight 1.18-1.9
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- freecam 1.0.8
	- gbfabrictools 1.3.4+1.19 via beenfo
	- ias 7.2.0
	- indium 1.0.5+mc1.19
	- inventorysorter 1.8.8-1.19
	- io_leangen_geantyref_geantyref 1.3.13 via bobby
	- iris 1.2.5
	- isxander-main-menu-credits 1.0.3
	- itemmodelfix 1.0.3+1.18
	- kappa 3.0.3
	- kyrptconfig 1.4.6-1.19 via inventorysorter
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.1.2+1.19
	- languagereload 1.3
	- lazydfu 0.1.3
	- lightoverlay 7.0.0
	- lithium 0.8.0
	- me_obsilabor_alert 1.0.6 via tpshud
	- memoryleakfix 1.19-0.4.1
	- midnightlib 0.5.2 via cullleaves
	- minecraft 1.19
	- modmenu 4.0.0
	- morechathistory 1.1.0
	- mousetweaks 2.22
	- nbteditor 1.6.0
	- nbttooltips 0.1.2-1.19
	- nofade 1.18-2.0.1
	- notenoughcrashes 4.1.6+1.19
	- omega-config 1.2.3-1.18.1 via capes
	- optigui 1.1.0
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_commons_commons-text 1.9 via optigui
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via bobby
	- org_spongepowered_configurate-hocon 4.1.2 via bobby
	- petowner 1.8.3-1.19+
	- pickblockpro 1.6.11
	- pride 1.1.2+1.19 via lambdynlights
	- puzzle 1.3.3
	- puzzle-base 1.3.3 via puzzle
	- puzzle-gui 1.3.3 via puzzle
	- puzzle-models 1.3.3 via puzzle
	- puzzle-splashscreen 1.3.3 via puzzle
	- reeses-sodium-options 1.4.3+mc1.19-build.43
	- replantingcrops-fabric 2.7
	- roughlyenoughitems 9.0.491
	- saveandloadinventories-fabric 1.8
	- securecrops 1.0.1-1.19
	- settxicloth 1.0.6 via zoomify
	- smoothboot 1.19-1.7.1
	- sodium 0.4.2+build.16
	- sodium-extra 0.4.5+mc1.19-build.43
	- spruceui 4.0.0+1.19 via lambdabettergrass
	- sspb 3.0.0
	- starlight 1.1.0+fabric.eb9df34
	- tooltipfix 1.0.5-1.19
	- torohealth 1.19-fabric-1
	- tpshud 1.4.1+1.19
	- tputils 1.6.12
	- trampledisablerfabric 1.0.6
	- visuality 0.5.0
	- voicechat 1.19-2.2.46
	- worldedit 7.2.11-beta-01+6200-0877589
	- wthit 5.4.1
	- xaerominimap 22.9.2
	- xaeroworldmap 1.23.2
	- yosbr 0.1.1
	- zoomify 1.7.0

**Comment by henkelmax** [comment] 2022-07-03 14:11
Does that also happen with a speed effect thats possible in survival?

**Comment by MichaMvz** [comment] 2022-07-03 14:22
I just found out its a problem with the options.txt after removing all my mods, I'll try to find out what causes this bug.

**Comment by MichaMvz** [comment] 2022-07-03 14:28
Ah it's the stupidest thing ever, it's the options FOV that breaks completely after FOV 90, which is my normal FOV. Does Camera utils use that fov for something?

**Comment by henkelmax** [comment] 2022-07-03 14:29
is this effect happening all the time or do you have to do something specific?

**Comment by MichaMvz** [comment] 2022-07-03 14:31
i have to set my FOV 90 or higher and set my effect speed to 9 or higher.

**Comment by henkelmax** [comment] 2022-07-03 14:32
Yes, but I was asking if this happens with a realistic speed value like 2

**Comment by MichaMvz** [comment] 2022-07-03 14:33
on speed 2 it makes your fov bearable, but higher than in normal mc

**Comment by henkelmax** [comment] 2022-07-03 14:34
So it doesn't happen with realistic values?

**Comment by MichaMvz** [comment] 2022-07-03 14:34
No.

**Comment by MichaMvz** [comment] 2022-07-03 14:35
Does camera utils use the fov double from the minecraft options? Because that uses a -1 to 1 scale, where 0.0 is 60

**Comment by henkelmax** [comment] 2022-07-03 14:35
> No.

Alright, thanks for testing it.

**Comment by henkelmax** [comment] 2022-07-03 14:36
> Does camera utils use the fov double from the minecraft options? Because that uses a -1 to 1 scale, where 0.0 is 60

This mod does not modify the FOV in normal gameplay

**Comment by MichaMvz** [comment] 2022-07-03 14:37
Then how come it does affect normal gameplay?

**Comment by henkelmax** [comment] 2022-07-03 14:38
Oh, can you send me a video of that (Without any other mods or effects)?

**Comment by MichaMvz** [comment] 2022-07-03 14:48
https://youtu.be/NSjCiJWZUQw

**Comment by MichaMvz** [comment] 2022-07-03 14:48
best is to wait for HD to stop processing

**Comment by henkelmax** [comment] 2022-07-03 14:49
Ah, I can see the issue, thanks for reporting this. I will investigate this further.

**Comment by MichaMvz** [comment] 2022-07-03 14:50
> Ah, I can see the issue, thanks for reporting this. I will investigate this further.

Thank you, please let me know when you've found the problem

**Comment by henkelmax** [comment] 2022-07-03 14:53
Sure

**Comment by henkelmax** [comment] 2022-07-03 14:58
I tested it myself and it works exactly like without the mod. Please try creating a new Minecraft instance without any other mods and the latest fabric version and mod version.

**Comment by MichaMvz** [comment] 2022-07-03 15:02
I tested it again with everything on the latest version. The bug still occurs.

**Comment by henkelmax** [comment] 2022-07-03 15:03
I'm sorry, but I can't reproduce it.

**Comment by MichaMvz** [comment] 2022-07-03 15:03
I'm testing it with the curseforge app, but i don't think that matters, right?

**Comment by henkelmax** [comment] 2022-07-03 15:04
No that shouldn't make a difference

**Comment by henkelmax** [comment] 2022-07-03 15:08
Both FOV 90 and speed 2:

![image](https://user-images.githubusercontent.com/13237524/177045773-3e487c13-75bb-42a0-8578-fde4b3307605.png)


First one is without the mod, second one is with

**Comment by MichaMvz** [comment] 2022-07-03 15:08
Test it with FOV 90 and speed 9

**Comment by henkelmax** [comment] 2022-07-03 15:09
That's not a realistic scenario. The most you can archive without commands is speed 2.

**Comment by MichaMvz** [comment] 2022-07-03 15:09
That is my problem, and i know some servers that use speed 9 or higher, and I'm planning on using it on a server i develop for, but this bug came along and is really annoying, because i love the features it brings and would hate it to have it disabled

**Comment by henkelmax** [comment] 2022-07-03 15:13
I'm sorry, but that's gonna be a wontfix. I might look into it in the future when I have more time, but not at the moment.

**Closed** 2022-07-03 15:15 UTC
Labels: bug, wontfix

**Comment by MichaMvz** [comment] 2022-07-03 15:17
Okay. Unfortunate.

**Comment by RigidStudios** [comment] 2022-12-19 13:45
@henkelmax This still occurs, I'm trying to use the mod on an RPG server (over-the-shoulder with your mod) where I regularly reach this speed, isn't this as simple as clamping the FOV value?
