### ISSUE TITLE
Better custom cameras

### ISSUE THREAD

**Issue by AmongstReality** [henkelmax/camera-utils#47] opened 2023-05-07 15:45 UTC
**Better custom cameras**
Can you make custom cameras a bit more dynamic, so they would stop clipping through walls. Also, it would be cool if you could use one key to switch between custom camera 1 and 2

**Comment by henkelmax** [comment] 2023-05-07 17:55
Duplicate of #6

**Closed by henkelmax** 2023-05-07 17:55 UTC
Labels: enhancement
